[package]
name = "cap_table_lib"
version = "0.1.0"
authors = ["Rick Price <rprice@pricemail.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.2"
serde_json = "1.0.44"
rusqlite = "0.21.0"
